// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace AspireOrchestrator.ScenarioTests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class StateMachineFeature : object, Xunit.IClassFixture<StateMachineFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "StateMachine", "Testing the State Machine", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "StateMap.feature"
#line hidden
        
        public StateMachineFeature(StateMachineFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="GetNextState")]
        [Xunit.TraitAttribute("FeatureTitle", "StateMachine")]
        [Xunit.TraitAttribute("Description", "GetNextState")]
        [Xunit.TraitAttribute("Category", "EventStates")]
        [Xunit.InlineDataAttribute("HandleReceipt", "Receive", "Parse", new string[0])]
        [Xunit.InlineDataAttribute("HandleReceipt", "Parse", "Validate", new string[0])]
        [Xunit.InlineDataAttribute("HandleReceipt", "Validate", "ProcessPayment", new string[0])]
        [Xunit.InlineDataAttribute("HandleReceipt", "ProcessPayment", "TransferResult", new string[0])]
        [Xunit.InlineDataAttribute("HandleReceipt", "TransferResult", "WorkFlowCompleted", new string[0])]
        [Xunit.InlineDataAttribute("HandleReceipt", "WorkFlowCompleted", "WorkFlowCompleted", new string[0])]
        [Xunit.InlineDataAttribute("HandleDeposit", "Receive", "Parse", new string[0])]
        [Xunit.InlineDataAttribute("HandleDeposit", "Parse", "ProcessPayment", new string[0])]
        [Xunit.InlineDataAttribute("HandleDeposit", "ProcessPayment", "TransferResult", new string[0])]
        [Xunit.InlineDataAttribute("HandleDeposit", "TransferResult", "WorkFlowCompleted", new string[0])]
        [Xunit.InlineDataAttribute("HandleDeposit", "WorkFlowCompleted", "WorkFlowCompleted", new string[0])]
        [Xunit.InlineDataAttribute("ValidateReceipt", "Validate", "ProcessPayment", new string[0])]
        [Xunit.InlineDataAttribute("ValidateReceipt", "ProcessPayment", "TransferResult", new string[0])]
        [Xunit.InlineDataAttribute("ValidateReceipt", "TransferResult", "WorkFlowCompleted", new string[0])]
        [Xunit.InlineDataAttribute("ValidateReceipt", "WorkFlowCompleted", "WorkFlowCompleted", new string[0])]
        public async global::System.Threading.Tasks.Task GetNextState(string event_Type, string process_State, string next_Process_State, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "EventStates"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Event_Type", event_Type);
            argumentsOfScenario.Add("Process_State", process_State);
            argumentsOfScenario.Add("Next_Process_State", next_Process_State);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("GetNextState", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
 await testRunner.WhenAsync(string.Format("the event with EventType {0} and ProcessState {1}", event_Type, process_State), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 8
 await testRunner.ThenAsync(string.Format("the ProcessState of the next event is {0}", next_Process_State), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await StateMachineFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await StateMachineFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
