// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace AspireOrchestrator.ScenarioTests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class WorkFlowFeature : object, Xunit.IClassFixture<WorkFlowFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "WorkFlow", "A short summary of the feature", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "WorkFlow.feature"
#line hidden
        
        public WorkFlowFeature(WorkFlowFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Receipt Workflow by event")]
        [Xunit.TraitAttribute("FeatureTitle", "WorkFlow")]
        [Xunit.TraitAttribute("Description", "Receipt Workflow by event")]
        [Xunit.TraitAttribute("Category", "tag1")]
        public async global::System.Threading.Tasks.Task ReceiptWorkflowByEvent()
        {
            string[] tagsOfScenario = new string[] {
                    "tag1"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Receipt Workflow by event", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "Event_Type",
                            "Process_State",
                            "TenantId",
                            "EventState",
                            "DocumentType",
                            "Parameters"});
                table1.AddRow(new string[] {
                            "HandleReceipt",
                            "Receive",
                            "1",
                            "New",
                            "IpStandard",
                            "{\"id\":\"71f1d54b-09be-463c-8676-88c5097ce4dd\"}"});
#line 7
 await testRunner.GivenAsync("the following event", ((string)(null)), table1, "Given ");
#line hidden
#line 11
 await testRunner.WhenAsync("the next event is processed", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "Event_Type",
                            "Process_State",
                            "TenantId",
                            "EventState",
                            "DocumentType",
                            "Parameters"});
                table2.AddRow(new string[] {
                            "HandleReceipt",
                            "Receive",
                            "1",
                            "Completed",
                            "IpStandard",
                            "{\"id\":\"71f1d54b-09be-463c-8676-88c5097ce4dd\"}"});
                table2.AddRow(new string[] {
                            "HandleReceipt",
                            "Parse",
                            "1",
                            "New",
                            "IpStandard",
                            "{\"id\":\"71f1d54b-09be-463c-8676-88c5097ce4dd\"}"});
#line 13
 await testRunner.ThenAsync("EventEntity table contains rows", ((string)(null)), table2, "Then ");
#line hidden
#line 17
 await testRunner.WhenAsync("the next event is processed", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "Event_Type",
                            "Process_State",
                            "TenantId",
                            "EventState"});
                table3.AddRow(new string[] {
                            "HandleReceipt",
                            "Receive",
                            "1",
                            "Completed"});
                table3.AddRow(new string[] {
                            "HandleReceipt",
                            "Parse",
                            "1",
                            "Completed"});
                table3.AddRow(new string[] {
                            "HandleReceipt",
                            "Validate",
                            "1",
                            "New"});
#line 19
 await testRunner.ThenAsync("EventEntity table contains rows", ((string)(null)), table3, "Then ");
#line hidden
#line 25
 await testRunner.WhenAsync("the next event is processed", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "Event_Type",
                            "Process_State",
                            "TenantId",
                            "EventState"});
                table4.AddRow(new string[] {
                            "HandleReceipt",
                            "Receive",
                            "1",
                            "Completed"});
                table4.AddRow(new string[] {
                            "HandleReceipt",
                            "Parse",
                            "1",
                            "Completed"});
                table4.AddRow(new string[] {
                            "HandleReceipt",
                            "Validate",
                            "1",
                            "Completed"});
                table4.AddRow(new string[] {
                            "HandleReceipt",
                            "ProcessPayment",
                            "1",
                            "New"});
#line 27
 await testRunner.ThenAsync("EventEntity table contains rows", ((string)(null)), table4, "Then ");
#line hidden
#line 34
 await testRunner.WhenAsync("the next event is processed", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "Event_Type",
                            "Process_State",
                            "TenantId",
                            "EventState"});
                table5.AddRow(new string[] {
                            "HandleReceipt",
                            "Receive",
                            "1",
                            "Completed"});
                table5.AddRow(new string[] {
                            "HandleReceipt",
                            "Parse",
                            "1",
                            "Completed"});
                table5.AddRow(new string[] {
                            "HandleReceipt",
                            "Validate",
                            "1",
                            "Completed"});
                table5.AddRow(new string[] {
                            "HandleReceipt",
                            "ProcessPayment",
                            "1",
                            "Completed"});
                table5.AddRow(new string[] {
                            "HandleReceipt",
                            "TransferResult",
                            "1",
                            "New"});
#line 36
 await testRunner.ThenAsync("EventEntity table contains rows", ((string)(null)), table5, "Then ");
#line hidden
#line 44
 await testRunner.WhenAsync("the next event is processed", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            "Event_Type",
                            "Process_State",
                            "TenantId",
                            "EventState"});
                table6.AddRow(new string[] {
                            "HandleReceipt",
                            "Receive",
                            "1",
                            "Completed"});
                table6.AddRow(new string[] {
                            "HandleReceipt",
                            "Parse",
                            "1",
                            "Completed"});
                table6.AddRow(new string[] {
                            "HandleReceipt",
                            "Validate",
                            "1",
                            "Completed"});
                table6.AddRow(new string[] {
                            "HandleReceipt",
                            "ProcessPayment",
                            "1",
                            "Completed"});
                table6.AddRow(new string[] {
                            "HandleReceipt",
                            "TransferResult",
                            "1",
                            "Completed"});
                table6.AddRow(new string[] {
                            "HandleReceipt",
                            "WorkFlowCompleted",
                            "1",
                            "Completed"});
#line 46
 await testRunner.ThenAsync("EventEntity table contains rows", ((string)(null)), table6, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Receipt Workflow by FlowId", Skip="Ignored")]
        [Xunit.TraitAttribute("FeatureTitle", "WorkFlow")]
        [Xunit.TraitAttribute("Description", "Receipt Workflow by FlowId")]
        [Xunit.TraitAttribute("Category", "tag1")]
        public async global::System.Threading.Tasks.Task ReceiptWorkflowByFlowId()
        {
            string[] tagsOfScenario = new string[] {
                    "tag1",
                    "ignore"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Receipt Workflow by FlowId", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 57
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table7 = new global::Reqnroll.Table(new string[] {
                            "Event_Type",
                            "Process_State",
                            "TenantId",
                            "EventState",
                            "FlowId"});
                table7.AddRow(new string[] {
                            "HandleReceipt",
                            "Receive",
                            "1",
                            "New",
                            "f80664bb-fe2c-422e-afc5-17a4eb6529cb"});
#line 58
 await testRunner.GivenAsync("the following event", ((string)(null)), table7, "Given ");
#line hidden
#line 62
 await testRunner.WhenAsync("the flow has been processed", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table8 = new global::Reqnroll.Table(new string[] {
                            "Event_Type",
                            "Process_State",
                            "TenantId",
                            "EventState",
                            "FlowId"});
                table8.AddRow(new string[] {
                            "HandleReceipt",
                            "Receive",
                            "1",
                            "Completed",
                            "f80664bb-fe2c-422e-afc5-17a4eb6529cb"});
                table8.AddRow(new string[] {
                            "HandleReceipt",
                            "Parse",
                            "1",
                            "Completed",
                            "f80664bb-fe2c-422e-afc5-17a4eb6529cb"});
                table8.AddRow(new string[] {
                            "HandleReceipt",
                            "Validate",
                            "1",
                            "Completed",
                            "f80664bb-fe2c-422e-afc5-17a4eb6529cb"});
                table8.AddRow(new string[] {
                            "HandleReceipt",
                            "ProcessPayment",
                            "1",
                            "Completed",
                            "f80664bb-fe2c-422e-afc5-17a4eb6529cb"});
                table8.AddRow(new string[] {
                            "HandleReceipt",
                            "TransferResult",
                            "1",
                            "Completed",
                            "f80664bb-fe2c-422e-afc5-17a4eb6529cb"});
                table8.AddRow(new string[] {
                            "HandleReceipt",
                            "WorkFlowCompleted",
                            "1",
                            "Completed",
                            "f80664bb-fe2c-422e-afc5-17a4eb6529cb"});
#line 64
 await testRunner.ThenAsync("EventEntity table contains rows", ((string)(null)), table8, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Deposit Workflow by FlowId", Skip="Ignored")]
        [Xunit.TraitAttribute("FeatureTitle", "WorkFlow")]
        [Xunit.TraitAttribute("Description", "Deposit Workflow by FlowId")]
        public async global::System.Threading.Tasks.Task DepositWorkflowByFlowId()
        {
            string[] tagsOfScenario = new string[] {
                    "ignore"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Deposit Workflow by FlowId", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 75
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table9 = new global::Reqnroll.Table(new string[] {
                            "Event_Type",
                            "Process_State",
                            "TenantId",
                            "EventState",
                            "FlowId"});
                table9.AddRow(new string[] {
                            "HandleDeposit",
                            "Receive",
                            "1",
                            "New",
                            "eb91261a-f9c0-4722-aa33-2e33d76186d6"});
#line 76
 await testRunner.GivenAsync("the following event", ((string)(null)), table9, "Given ");
#line hidden
#line 80
 await testRunner.WhenAsync("the flow has been processed", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table10 = new global::Reqnroll.Table(new string[] {
                            "Event_Type",
                            "Process_State",
                            "TenantId",
                            "EventState",
                            "FlowId"});
                table10.AddRow(new string[] {
                            "HandleDeposit",
                            "Receive",
                            "1",
                            "Completed",
                            "eb91261a-f9c0-4722-aa33-2e33d76186d6"});
                table10.AddRow(new string[] {
                            "HandleDeposit",
                            "Parse",
                            "1",
                            "Completed",
                            "eb91261a-f9c0-4722-aa33-2e33d76186d6"});
                table10.AddRow(new string[] {
                            "HandleDeposit",
                            "ProcessPayment",
                            "1",
                            "Completed",
                            "eb91261a-f9c0-4722-aa33-2e33d76186d6"});
                table10.AddRow(new string[] {
                            "HandleDeposit",
                            "TransferResult",
                            "1",
                            "Completed",
                            "eb91261a-f9c0-4722-aa33-2e33d76186d6"});
                table10.AddRow(new string[] {
                            "HandleDeposit",
                            "WorkFlowCompleted",
                            "1",
                            "Completed",
                            "eb91261a-f9c0-4722-aa33-2e33d76186d6"});
#line 82
 await testRunner.ThenAsync("EventEntity table contains rows", ((string)(null)), table10, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await WorkFlowFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await WorkFlowFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
