// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AspireOrchestrator.ScenarioTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class WorkFlowFeature : object, Xunit.IClassFixture<WorkFlowFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "WorkFlow.feature"
#line hidden
        
        public WorkFlowFeature(WorkFlowFeature.FixtureData fixtureData, AspireOrchestrator_ScenarioTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "WorkFlow", "A short summary of the feature", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="PDF Workflow by event")]
        [Xunit.TraitAttribute("FeatureTitle", "WorkFlow")]
        [Xunit.TraitAttribute("Description", "PDF Workflow by event")]
        [Xunit.TraitAttribute("Category", "tag1")]
        public void PDFWorkflowByEvent()
        {
            string[] tagsOfScenario = new string[] {
                    "tag1"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PDF Workflow by event", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "Event_Type",
                            "Process_State",
                            "TenantId",
                            "EventState",
                            "FlowId"});
                table1.AddRow(new string[] {
                            "HandlePdf",
                            "Receive",
                            "1",
                            "New",
                            "123"});
#line 7
 testRunner.Given("the following event", ((string)(null)), table1, "Given ");
#line hidden
#line 11
 testRunner.When("the next event is processed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "Event_Type",
                            "Process_State",
                            "TenantId",
                            "EventState",
                            "FlowId"});
                table2.AddRow(new string[] {
                            "HandlePdf",
                            "Receive",
                            "1",
                            "Completed",
                            "123"});
                table2.AddRow(new string[] {
                            "HandlePdf",
                            "Parse",
                            "1",
                            "New",
                            "123"});
#line 13
 testRunner.Then("EventEntity table contains rows", ((string)(null)), table2, "Then ");
#line hidden
#line 17
 testRunner.When("the next event is processed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "Event_Type",
                            "Process_State",
                            "TenantId",
                            "EventState",
                            "FlowId"});
                table3.AddRow(new string[] {
                            "HandlePdf",
                            "Receive",
                            "1",
                            "Completed",
                            "123"});
                table3.AddRow(new string[] {
                            "HandlePdf",
                            "Parse",
                            "1",
                            "Completed",
                            "123"});
                table3.AddRow(new string[] {
                            "HandlePdf",
                            "Convert",
                            "1",
                            "New",
                            "123"});
#line 19
 testRunner.Then("EventEntity table contains rows", ((string)(null)), table3, "Then ");
#line hidden
#line 25
 testRunner.When("the next event is processed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "Event_Type",
                            "Process_State",
                            "TenantId",
                            "EventState",
                            "FlowId"});
                table4.AddRow(new string[] {
                            "HandlePdf",
                            "Receive",
                            "1",
                            "Completed",
                            "123"});
                table4.AddRow(new string[] {
                            "HandlePdf",
                            "Parse",
                            "1",
                            "Completed",
                            "123"});
                table4.AddRow(new string[] {
                            "HandlePdf",
                            "Convert",
                            "1",
                            "Completed",
                            "123"});
                table4.AddRow(new string[] {
                            "HandlePdf",
                            "Validate",
                            "1",
                            "New",
                            "123"});
#line 27
 testRunner.Then("EventEntity table contains rows", ((string)(null)), table4, "Then ");
#line hidden
#line 34
 testRunner.When("the next event is processed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "Event_Type",
                            "Process_State",
                            "TenantId",
                            "EventState",
                            "FlowId"});
                table5.AddRow(new string[] {
                            "HandlePdf",
                            "Receive",
                            "1",
                            "Completed",
                            "123"});
                table5.AddRow(new string[] {
                            "HandlePdf",
                            "Parse",
                            "1",
                            "Completed",
                            "123"});
                table5.AddRow(new string[] {
                            "HandlePdf",
                            "Convert",
                            "1",
                            "Completed",
                            "123"});
                table5.AddRow(new string[] {
                            "HandlePdf",
                            "Validate",
                            "1",
                            "Completed",
                            "123"});
                table5.AddRow(new string[] {
                            "HandlePdf",
                            "Process",
                            "1",
                            "New",
                            "123"});
#line 36
 testRunner.Then("EventEntity table contains rows", ((string)(null)), table5, "Then ");
#line hidden
#line 44
 testRunner.When("the next event is processed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                            "Event_Type",
                            "Process_State",
                            "TenantId",
                            "EventState",
                            "FlowId"});
                table6.AddRow(new string[] {
                            "HandlePdf",
                            "Receive",
                            "1",
                            "Completed",
                            "123"});
                table6.AddRow(new string[] {
                            "HandlePdf",
                            "Parse",
                            "1",
                            "Completed",
                            "123"});
                table6.AddRow(new string[] {
                            "HandlePdf",
                            "Convert",
                            "1",
                            "Completed",
                            "123"});
                table6.AddRow(new string[] {
                            "HandlePdf",
                            "Validate",
                            "1",
                            "Completed",
                            "123"});
                table6.AddRow(new string[] {
                            "HandlePdf",
                            "Process",
                            "1",
                            "Completed",
                            "123"});
                table6.AddRow(new string[] {
                            "HandlePdf",
                            "GenerateReceipt",
                            "1",
                            "New",
                            "123"});
#line 46
 testRunner.Then("EventEntity table contains rows", ((string)(null)), table6, "Then ");
#line hidden
#line 55
 testRunner.When("the next event is processed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                            "Event_Type",
                            "Process_State",
                            "TenantId",
                            "EventState",
                            "FlowId"});
                table7.AddRow(new string[] {
                            "HandlePdf",
                            "Receive",
                            "1",
                            "Completed",
                            "123"});
                table7.AddRow(new string[] {
                            "HandlePdf",
                            "Parse",
                            "1",
                            "Completed",
                            "123"});
                table7.AddRow(new string[] {
                            "HandlePdf",
                            "Convert",
                            "1",
                            "Completed",
                            "123"});
                table7.AddRow(new string[] {
                            "HandlePdf",
                            "Validate",
                            "1",
                            "Completed",
                            "123"});
                table7.AddRow(new string[] {
                            "HandlePdf",
                            "Process",
                            "1",
                            "Completed",
                            "123"});
                table7.AddRow(new string[] {
                            "HandlePdf",
                            "GenerateReceipt",
                            "1",
                            "Completed",
                            "123"});
                table7.AddRow(new string[] {
                            "HandlePdf",
                            "TransferResult",
                            "1",
                            "New",
                            "123"});
#line 57
 testRunner.Then("EventEntity table contains rows", ((string)(null)), table7, "Then ");
#line hidden
#line 67
 testRunner.When("the next event is processed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                            "Event_Type",
                            "Process_State",
                            "TenantId",
                            "EventState",
                            "FlowId"});
                table8.AddRow(new string[] {
                            "HandlePdf",
                            "Receive",
                            "1",
                            "Completed",
                            "123"});
                table8.AddRow(new string[] {
                            "HandlePdf",
                            "Parse",
                            "1",
                            "Completed",
                            "123"});
                table8.AddRow(new string[] {
                            "HandlePdf",
                            "Convert",
                            "1",
                            "Completed",
                            "123"});
                table8.AddRow(new string[] {
                            "HandlePdf",
                            "Validate",
                            "1",
                            "Completed",
                            "123"});
                table8.AddRow(new string[] {
                            "HandlePdf",
                            "Process",
                            "1",
                            "Completed",
                            "123"});
                table8.AddRow(new string[] {
                            "HandlePdf",
                            "GenerateReceipt",
                            "1",
                            "Completed",
                            "123"});
                table8.AddRow(new string[] {
                            "HandlePdf",
                            "TransferResult",
                            "1",
                            "Completed",
                            "123"});
                table8.AddRow(new string[] {
                            "HandlePdf",
                            "WorkFlowCompleted",
                            "1",
                            "Completed",
                            "123"});
#line 69
 testRunner.Then("EventEntity table contains rows", ((string)(null)), table8, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="PDF Workflow by FlowId")]
        [Xunit.TraitAttribute("FeatureTitle", "WorkFlow")]
        [Xunit.TraitAttribute("Description", "PDF Workflow by FlowId")]
        [Xunit.TraitAttribute("Category", "tag1")]
        public void PDFWorkflowByFlowId()
        {
            string[] tagsOfScenario = new string[] {
                    "tag1"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PDF Workflow by FlowId", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 81
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                            "Event_Type",
                            "Process_State",
                            "TenantId",
                            "EventState",
                            "FlowId"});
                table9.AddRow(new string[] {
                            "HandlePdf",
                            "Receive",
                            "1",
                            "New",
                            "124"});
#line 82
 testRunner.Given("the following event", ((string)(null)), table9, "Given ");
#line hidden
#line 86
 testRunner.When("the flow has been processed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                            "Event_Type",
                            "Process_State",
                            "TenantId",
                            "EventState",
                            "FlowId"});
                table10.AddRow(new string[] {
                            "HandlePdf",
                            "Receive",
                            "1",
                            "Completed",
                            "124"});
                table10.AddRow(new string[] {
                            "HandlePdf",
                            "Parse",
                            "1",
                            "Completed",
                            "124"});
                table10.AddRow(new string[] {
                            "HandlePdf",
                            "Convert",
                            "1",
                            "Completed",
                            "124"});
                table10.AddRow(new string[] {
                            "HandlePdf",
                            "Validate",
                            "1",
                            "Completed",
                            "124"});
                table10.AddRow(new string[] {
                            "HandlePdf",
                            "Process",
                            "1",
                            "Completed",
                            "124"});
                table10.AddRow(new string[] {
                            "HandlePdf",
                            "GenerateReceipt",
                            "1",
                            "Completed",
                            "124"});
                table10.AddRow(new string[] {
                            "HandlePdf",
                            "TransferResult",
                            "1",
                            "Completed",
                            "124"});
                table10.AddRow(new string[] {
                            "HandlePdf",
                            "WorkFlowCompleted",
                            "1",
                            "Completed",
                            "124"});
#line 88
 testRunner.Then("EventEntity table contains rows", ((string)(null)), table10, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                WorkFlowFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                WorkFlowFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
